name: Run Selenium Tests

on:
  push:
    branches:
      - main

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Descargar tu código
    - name: Checkout code
      uses: actions/checkout@v3


    # Paso 3: Verificar versiones (opcional, para depuración)
    - name: Check Chrome and ChromeDriver version
      run: |
        google-chrome --version
        chromedriver --version

    # Paso 4: Configurar y ejecutar pruebas
    - name: Run Selenium Tests
      run: mvn test  # Cambia este comando si usas otro para ejecutar tus pruebas
