name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Configurar Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'   # Puedes cambiar a 'zulu' u otro proveedor si es necesario
          java-version: '17'        # Cambia según la versión que uses

      # Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Instalar dependencias de Node.js
      - name: Install Node.js dependencies
        run: npm install

      # Ejecutar pruebas de Node.js
      - name: Run Node.js tests
        run: npm test

      # Configurar Maven o Gradle (elige uno según tu proyecto)
      - name: Set up Maven
        run: mvn -version         # Verifica que Maven está disponible (opcional)

      # Instalar dependencias de Maven
      - name: Install Maven dependencies
        run: mvn clean install    # Cambia por Gradle si lo usas

      # Ejecutar pruebas de Cucumber
      - name: Run Cucumber tests
        run: mvn test             # Cambia a `gradle test` si usas Gradle
 
