name: CI

on:
  push:
    branches:
      
main
pull_request:
  branches:
main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      
name: Checkout code
      uses: actions/checkout@v2

      
name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Cambia esto a la versión de Node.js que estés usando

      
name: Install dependencies
      run: npm install

      
name: Fix permissions
      run: chmod +x ./node_modules/.bin/jest  # Asegura permisos para jest

      
name: Run tests
      run: npm test
